package com.all_i.allibe.member.domain.enums;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@Getter
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@ToString
public enum Region {

    // 서울특별시
    SEOUL_JONGNO("서울특별시", "종로구"),
    SEOUL_JUNG("서울특별시", "중구"),
    SEOUL_YONGSAN("서울특별시", "용산구"),
    SEOUL_SEONGDONG("서울특별시", "성동구"),
    SEOUL_GWANGJIN("서울특별시", "광진구"),
    SEOUL_DONGDAEMUN("서울특별시", "동대문구"),
    SEOUL_JUNGNANG("서울특별시", "중랑구"),
    SEOUL_SEONGBUK("서울특별시", "성북구"),
    SEOUL_GANGBUK("서울특별시", "강북구"),
    SEOUL_DOBONG("서울특별시", "도봉구"),
    SEOUL_NOWON("서울특별시", "노원구"),
    SEOUL_EUNPYEONG("서울특별시", "은평구"),
    SEOUL_SEODAEMUN("서울특별시", "서대문구"),
    SEOUL_MAPO("서울특별시", "마포구"),
    SEOUL_YANGCHEON("서울특별시", "양천구"),
    SEOUL_GANGSEO("서울특별시", "강서구"),
    SEOUL_GURO("서울특별시", "구로구"),
    SEOUL_GEUMCHEON("서울특별시", "금천구"),
    SEOUL_YEONGDEUNGPO("서울특별시", "영등포구"),
    SEOUL_DONGJAK("서울특별시", "동작구"),
    SEOUL_GWANAK("서울특별시", "관악구"),
    SEOUL_SEOCHO("서울특별시", "서초구"),
    SEOUL_GANGNAM("서울특별시", "강남구"),
    SEOUL_SONGPA("서울특별시", "송파구"),
    SEOUL_GANGDONG("서울특별시", "강동구"),

    // 부산광역시
    BUSAN_JUNG("부산광역시", "중구"),
    BUSAN_SEO("부산광역시", "서구"),
    BUSAN_DONG("부산광역시", "동구"),
    BUSAN_YEONGDO("부산광역시", "영도구"),
    BUSAN_BUSANJIN("부산광역시", "부산진구"),
    BUSAN_DONGNAE("부산광역시", "동래구"),
    BUSAN_NAM("부산광역시", "남구"),
    BUSAN_BUK("부산광역시", "북구"),
    BUSAN_HAEUNDAE("부산광역시", "해운대구"),
    BUSAN_SAHA("부산광역시", "사하구"),
    BUSAN_GEUMJEONG("부산광역시", "금정구"),
    BUSAN_GANGSEO("부산광역시", "강서구"),
    BUSAN_YEONJE("부산광역시", "연제구"),
    BUSAN_SUYEONG("부산광역시", "수영구"),
    BUSAN_SASANG("부산광역시", "사상구"),
    BUSAN_GIJANG("부산광역시", "기장군"),

    // 인천광역시
    INCHEON_JUNG("인천광역시", "중구"),
    INCHEON_DONG("인천광역시", "동구"),
    INCHEON_MICHUHOL("인천광역시", "미추홀구"),
    INCHEON_YEONSU("인천광역시", "연수구"),
    INCHEON_NAMDONG("인천광역시", "남동구"),
    INCHEON_BUPYEONG("인천광역시", "부평구"),
    INCHEON_GYEYANG("인천광역시", "계양구"),
    INCHEON_SEOKU("인천광역시", "서구"),
    INCHEON_GANGHWA("인천광역시", "강화군"),
    INCHEON_ONGJIN("인천광역시", "옹진군"),

    // 대구광역시
    DAEGU_JUNG("대구광역시", "중구"),
    DAEGU_DONG("대구광역시", "동구"),
    DAEGU_SEO("대구광역시", "서구"),
    DAEGU_NAM("대구광역시", "남구"),
    DAEGU_BUK("대구광역시", "북구"),
    DAEGU_SUSEONG("대구광역시", "수성구"),
    DAEGU_DALSEO("대구광역시", "달서구"),
    DAEGU_DALSEONG("대구광역시", "달성군"),
    DAEGU_GUNWI("대구광역시", "군위군"),

    // 광주광역시
    GWANGJU_DONG("광주광역시", "동구"),
    GWANGJU_SEO("광주광역시", "서구"),
    GWANGJU_NAM("광주광역시", "남구"),
    GWANGJU_BUK("광주광역시", "북구"),
    GWANGJU_GWANGSAN("광주광역시", "광산구"),

    // 대전광역시
    DAEJEON_DONG("대전광역시", "동구"),
    DAEJEON_JUNG("대전광역시", "중구"),
    DAEJEON_SEO("대전광역시", "서구"),
    DAEJEON_YUSEONG("대전광역시", "유성구"),
    DAEJEON_DAEDEOK("대전광역시", "대덕구"),

    // 울산광역시
    ULSAN_JUNG("울산광역시", "중구"),
    ULSAN_NAM("울산광역시", "남구"),
    ULSAN_DONG("울산광역시", "동구"),
    ULSAN_BUK("울산광역시", "북구"),
    ULSAN_ULJU("울산광역시", "울주군"),

    // 경기도
    GYEONGGI_SUWON("경기도", "수원시"),
    GYEONGGI_YONGIN("경기도", "용인시"),
    GYEONGGI_GOYANG("경기도", "고양시"),
    GYEONGGI_HWASEONG("경기도", "화성시"),
    GYEONGGI_SEONGNAM("경기도", "성남시"),
    GYEONGGI_BUCHEON("경기도", "부천시"),
    GYEONGGI_NAMYANGJU("경기도", "남양주시"),
    GYEONGGI_ANSAN("경기도", "안산시"),
    GYEONGGI_PYEONGTAEK("경기도", "평택시"),
    GYEONGGI_ANYANG("경기도", "안양시"),
    GYEONGGI_SIHEUNG("경기도", "시흥시"),
    GYEONGGI_PAJU("경기도", "파주시"),
    GYEONGGI_GIMPO("경기도", "김포시"),
    GYEONGGI_UIJEONGBU("경기도", "의정부시"),
    GYEONGGI_GWANGJU("경기도", "광주시"),
    GYEONGGI_HANAM("경기도", "하남시"),
    GYEONGGI_GWANGMYEONG("경기도", "광명시"),
    GYEONGGI_GUNPO("경기도", "군포시"),
    GYEONGGI_YANGJU("경기도", "양주시"),
    GYEONGGI_OSAN("경기도", "오산시"),
    GYEONGGI_ICHEON("경기도", "이천시"),
    GYEONGGI_ANSEONG("경기도", "안성시"),
    GYEONGGI_GURI("경기도", "구리시"),
    GYEONGGI_UIWANG("경기도", "의왕시"),
    GYEONGGI_POCHEON("경기도", "포천시"),
    GYEONGGI_YANGPYEONG("경기도", "양평군"),
    GYEONGGI_YEOJU("경기도", "여주시"),
    GYEONGGI_DONGDUCHEON("경기도", "동두천시"),
    GYEONGGI_GWACHEON("경기도", "과천시"),
    GYEONGGI_GAPYEONG("경기도", "가평군"),
    GYEONGGI_YEONCHEON("경기도", "연천군"),

    // 강원특별자치도
    GANGWON_CHUNCHEON("강원특별자치도", "춘천시"),
    GANGWON_WONJU("강원특별자치도", "원주시"),
    GANGWON_GANGNEUNG("강원특별자치도", "강릉시"),
    GANGWON_DONGHAE("강원특별자치도", "동해시"),
    GANGWON_TAEBAEK("강원특별자치도", "태백시"),
    GANGWON_SOKCHO("강원특별자치도", "속초시"),
    GANGWON_SAMCHEOK("강원특별자치도", "삼척시"),
    GANGWON_HONGCHEON("강원특별자치도", "홍천군"),
    GANGWON_HOENGSEONG("강원특별자치도", "횡성군"),
    GANGWON_YEONGWOL("강원특별자치도", "영월군"),
    GANGWON_PYEONGCHANG("강원특별자치도", "평창군"),
    GANGWON_JEONGSEON("강원특별자치도", "정선군"),
    GANGWON_CHEORWON("강원특별자치도", "철원군"),
    GANGWON_HWACHEON("강원특별자치도", "화천군"),
    GANGWON_YANGGU("강원특별자치도", "양구군"),
    GANGWON_INJE("강원특별자치도", "인제군"),
    GANGWON_GOSEONG("강원특별자치도", "고성군"),
    GANGWON_YANGYANG("강원특별자치도", "양양군"),

    // 충청북도
    CHUNGBUK_CHEONGJU("충청북도", "청주시"),
    CHUNGBUK_CHUNGJU("충청북도", "충주시"),
    CHUNGBUK_JECHEON("충청북도", "제천시"),
    CHUNGBUK_BOEUN("충청북도", "보은군"),
    CHUNGBUK_OKCHEON("충청북도", "옥천군"),
    CHUNGBUK_YEONGDONG("충청북도", "영동군"),
    CHUNGBUK_JEUNGPYEONG("충청북도", "증평군"),
    CHUNGBUK_JINCHEON("충청북도", "진천군"),
    CHUNGBUK_GOESAN("충청북도", "괴산군"),
    CHUNGBUK_EUMSEONG("충청북도", "음성군"),
    CHUNGBUK_DANYANG("충청북도", "단양군"),

    // 충청남도
    CHUNGNAM_CHEONAN("충청남도", "천안시"),
    CHUNGNAM_GONGJU("충청남도", "공주시"),
    CHUNGNAM_BORYEONG("충청남도", "보령시"),
    CHUNGNAM_ASAN("충청남도", "아산시"),
    CHUNGNAM_SEOSAN("충청남도", "서산시"),
    CHUNGNAM_NONSAN("충청남도", "논산시"),
    CHUNGNAM_GYERYONG("충청남도", "계룡시"),
    CHUNGNAM_DANGJIN("충청남도", "당진시"),
    CHUNGNAM_GEUMSAN("충청남도", "금산군"),
    CHUNGNAM_BUYEO("충청남도", "부여군"),
    CHUNGNAM_SEOCHEON("충청남도", "서천군"),
    CHUNGNAM_CHEONGYANG("충청남도", "청양군"),
    CHUNGNAM_HONGSEONG("충청남도", "홍성군"),
    CHUNGNAM_YESAN("충청남도", "예산군"),
    CHUNGNAM_TAEAN("충청남도", "태안군"),

    // 전북특별자치도
    JEONBUK_JEONJU("전북특별자치도", "전주시"),
    JEONBUK_GUNSAN("전북특별자치도", "군산시"),
    JEONBUK_IKSAN("전북특별자치도", "익산시"),
    JEONBUK_JEONGEUP("전북특별자치도", "정읍시"),
    JEONBUK_NAMWON("전북특별자치도", "남원시"),
    JEONBUK_GIMJE("전북특별자치도", "김제시"),
    JEONBUK_WANJU("전북특별자치도", "완주군"),
    JEONBUK_JINAN("전북특별자치도", "진안군"),
    JEONBUK_MUJU("전북특별자치도", "무주군"),
    JEONBUK_JANGSU("전북특별자치도", "장수군"),
    JEONBUK_IMSIL("전북특별자치도", "임실군"),
    JEONBUK_SUNCHANG("전북특별자치도", "순창군"),
    JEONBUK_GOCHANG("전북특별자치도", "고창군"),
    JEONBUK_BUAN("전북특별자치도", "부안군"),

    // 전라남도
    JEONNAM_MOKPO("전라남도", "목포시"),
    JEONNAM_YEOSU("전라남도", "여수시"),
    JEONNAM_SUNCHEON("전라남도", "순천시"),
    JEONNAM_NAJU("전라남도", "나주시"),
    JEONNAM_GWANGYANG("전라남도", "광양시"),
    JEONNAM_DAMYANG("전라남도", "담양군"),
    JEONNAM_GOKSEONG("전라남도", "곡성군"),
    JEONNAM_GURYE("전라남도", "구례군"),
    JEONNAM_GOHEUNG("전라남도", "고흥군"),
    JEONNAM_BOSEONG("전라남도", "보성군"),
    JEONNAM_HWASUN("전라남도", "화순군"),
    JEONNAM_JANGHEUNG("전라남도", "장흥군"),
    JEONNAM_GANGJIN("전라남도", "강진군"),
    JEONNAM_HAENAM("전라남도", "해남군"),
    JEONNAM_YEONGAM("전라남도", "영암군"),
    JEONNAM_MUAN("전라남도", "무안군"),
    JEONNAM_HAMPYEONG("전라남도", "함평군"),
    JEONNAM_YEONGGWANG("전라남도", "영광군"),
    JEONNAM_JANGSEONG("전라남도", "장성군"),
    JEONNAM_WANDO("전라남도", "완도군"),
    JEONNAM_JINDO("전라남도", "진도군"),
    JEONNAM_SINAN("전라남도", "신안군"),

    // 경상북도
    GYEONGBUK_POHANG("경상북도", "포항시"),
    GYEONGBUK_GYEONGJU("경상북도", "경주시"),
    GYEONGBUK_GIMCHEON("경상북도", "김천시"),
    GYEONGBUK_ANDONG("경상북도", "안동시"),
    GYEONGBUK_GUMI("경상북도", "구미시"),
    GYEONGBUK_YEONGJU("경상북도", "영주시"),
    GYEONGBUK_YEONGCHEON("경상북도", "영천시"),
    GYEONGBUK_SANGJU("경상북도", "상주시"),
    GYEONGBUK_MUNGYEONG("경상북도", "문경시"),
    GYEONGBUK_GYEONGSAN("경상북도", "경산시"),
    GYEONGBUK_UISEONG("경상북도", "의성군"),
    GYEONGBUK_CHEONGSONG("경상북도", "청송군"),
    GYEONGBUK_YEONGYANG("경상북도", "영양군"),
    GYEONGBUK_YEONGDEOK("경상북도", "영덕군"),
    GYEONGBUK_CHEONGDO("경상북도", "청도군"),
    GYEONGBUK_GORYEONG("경상북도", "고령군"),
    GYEONGBUK_SEONGJU("경상북도", "성주군"),
    GYEONGBUK_CHILGOK("경상북도", "칠곡군"),
    GYEONGBUK_YECHEON("경상북도", "예천군"),
    GYEONGBUK_BONGHWA("경상북도", "봉화군"),
    GYEONGBUK_ULJIN("경상북도", "울진군"),
    GYEONGBUK_ULLEUNG("경상북도", "울릉군"),

    // 경상남도
    GYEONGNAM_CHANGWON("경상남도", "창원시"),
    GYEONGNAM_JINJU("경상남도", "진주시"),
    GYEONGNAM_TONGYEONG("경상남도", "통영시"),
    GYEONGNAM_SACHEON("경상남도", "사천시"),
    GYEONGNAM_GIMHAE("경상남도", "김해시"),
    GYEONGNAM_MIRYANG("경상남도", "밀양시"),
    GYEONGNAM_GEOJE("경상남도", "거제시"),
    GYEONGNAM_YANGSAN("경상남도", "양산시"),
    GYEONGNAM_UIRYEONG("경상남도", "의령군"),
    GYEONGNAM_HAMAN("경상남도", "함안군"),
    GYEONGNAM_CHANGNYEONG("경상남도", "창녕군"),
    GYEONGNAM_GOSEONG("경상남도", "고성군"),
    GYEONGNAM_NAMHAE("경상남도", "남해군"),
    GYEONGNAM_HADONG("경상남도", "하동군"),
    GYEONGNAM_SANCHEONG("경상남도", "산청군"),
    GYEONGNAM_HAMYANG("경상남도", "함양군"),
    GYEONGNAM_GEOCHANG("경상남도", "거창군"),
    GYEONGNAM_HAPCHEON("경상남도", "합천군"),

    // 제주특별자치도
    JEJU_JEJU("제주특별자치도", "제주시"),
    JEJU_SEOGWIPO("제주특별자치도", "서귀포시");
    ;

    private String city;
    private String district;

}
