image: node:22.11.0

stages:
    - deploy

pages:
    stage: deploy
    script:
        - cd FE
        - npm install
        - npm run build
        - mv dist public

    artifacts:
        paths:
            - FE/public
    only:
        - dev-FE
