
###
POST http://localhost:8080/api/v1/follow/request
Content-Type: application/json
Authorization: Bearer {{TEST_ACCESS_TOKEN}}

{
  "recipientId": 3
}

###
PATCH http://localhost:8080/api/v1/follow/request/handle
Content-Type: application/json
Authorization: Bearer {{TEST_ACCESS_TOKEN}}

{
  "requesterId": 2,
  "status": "ACCEPT"
}

###
GET http://localhost:8080/api/v1/follow/me/follower
Authorization: Bearer {{TEST_ACCESS_TOKEN}}

###
GET http://localhost:8080/api/v1/follow/me/following
Authorization: Bearer {{TEST_ACCESS_TOKEN}}