export const regionData: Record<string, { label: string; value: string }[]> = {
    서울특별시: [
        { label: "종로구", value: "SEOUL_JONGNO" },
        { label: "중구", value: "SEOUL_JUNG" },
        { label: "용산구", value: "SEOUL_YONGSAN" },
        { label: "성동구", value: "SEOUL_SEONGDONG" },
        { label: "광진구", value: "SEOUL_GWANGJIN" },
        { label: "동대문구", value: "SEOUL_DONGDAEMUN" },
        { label: "중랑구", value: "SEOUL_JUNGNANG" },
        { label: "성북구", value: "SEOUL_SEONGBUK" },
        { label: "강북구", value: "SEOUL_GANGBUK" },
        { label: "도봉구", value: "SEOUL_DOBONG" },
        { label: "노원구", value: "SEOUL_NOWON" },
        { label: "은평구", value: "SEOUL_EUNPYEONG" },
        { label: "서대문구", value: "SEOUL_SEODAEMUN" },
        { label: "마포구", value: "SEOUL_MAPO" },
        { label: "양천구", value: "SEOUL_YANGCHEON" },
        { label: "강서구", value: "SEOUL_GANGSEO" },
        { label: "구로구", value: "SEOUL_GURO" },
        { label: "금천구", value: "SEOUL_GEUMCHEON" },
        { label: "영등포구", value: "SEOUL_YEONGDEUNGPO" },
        { label: "동작구", value: "SEOUL_DONGJAK" },
        { label: "관악구", value: "SEOUL_GWANAK" },
        { label: "서초구", value: "SEOUL_SEOCHO" },
        { label: "강남구", value: "SEOUL_GANGNAM" },
        { label: "송파구", value: "SEOUL_SONGPA" },
        { label: "강동구", value: "SEOUL_GANGDONG" },
    ],
    부산광역시: [
        { label: "중구", value: "BUSAN_JUNG" },
        { label: "서구", value: "BUSAN_SEO" },
        { label: "동구", value: "BUSAN_DONG" },
        { label: "영도구", value: "BUSAN_YEONGDO" },
        { label: "부산진구", value: "BUSAN_BUSANJIN" },
        { label: "동래구", value: "BUSAN_DONGNAE" },
        { label: "남구", value: "BUSAN_NAM" },
        { label: "북구", value: "BUSAN_BUK" },
        { label: "해운대구", value: "BUSAN_HAEUNDAE" },
        { label: "사하구", value: "BUSAN_SAHA" },
        { label: "금정구", value: "BUSAN_GEUMJEONG" },
        { label: "강서구", value: "BUSAN_GANGSEO" },
        { label: "연제구", value: "BUSAN_YEONJE" },
        { label: "수영구", value: "BUSAN_SUYEONG" },
        { label: "사상구", value: "BUSAN_SASANG" },
        { label: "기장군", value: "BUSAN_GIJANG" },
    ],
    인천광역시: [
        { label: "중구", value: "INCHEON_JUNG" },
        { label: "동구", value: "INCHEON_DONG" },
        { label: "미추홀구", value: "INCHEON_MICHUHOL" },
        { label: "연수구", value: "INCHEON_YEONSU" },
        { label: "남동구", value: "INCHEON_NAMDONG" },
        { label: "부평구", value: "INCHEON_BUPYEONG" },
        { label: "계양구", value: "INCHEON_GYEYANG" },
        { label: "서구", value: "INCHEON_SEOKU" },
        { label: "강화군", value: "INCHEON_GANGHWA" },
        { label: "옹진군", value: "INCHEON_ONGJIN" },
    ],
    대구광역시: [
        { label: "중구", value: "DAEGU_JUNG" },
        { label: "동구", value: "DAEGU_DONG" },
        { label: "서구", value: "DAEGU_SEO" },
        { label: "남구", value: "DAEGU_NAM" },
        { label: "북구", value: "DAEGU_BUK" },
        { label: "수성구", value: "DAEGU_SUSEONG" },
        { label: "달서구", value: "DAEGU_DALSEO" },
        { label: "달성군", value: "DAEGU_DALSEONG" },
        { label: "군위군", value: "DAEGU_GUNWI" },
    ],
    광주광역시: [
        { label: "동구", value: "GWANGJU_DONG" },
        { label: "서구", value: "GWANGJU_SEO" },
        { label: "남구", value: "GWANGJU_NAM" },
        { label: "북구", value: "GWANGJU_BUK" },
        { label: "광산구", value: "GWANGJU_GWANGSAN" },
    ],
    대전광역시: [
        { label: "동구", value: "DAEJEON_DONG" },
        { label: "중구", value: "DAEJEON_JUNG" },
        { label: "서구", value: "DAEJEON_SEO" },
        { label: "유성구", value: "DAEJEON_YUSEONG" },
        { label: "대덕구", value: "DAEJEON_DAEDEOK" },
    ],
    울산광역시: [
        { label: "중구", value: "ULSAN_JUNG" },
        { label: "남구", value: "ULSAN_NAM" },
        { label: "동구", value: "ULSAN_DONG" },
        { label: "북구", value: "ULSAN_BUK" },
        { label: "울주군", value: "ULSAN_ULJU" },
    ],
    경기도: [
        { label: "수원시", value: "GYEONGGI_SUWON" },
        { label: "용인시", value: "GYEONGGI_YONGIN" },
        { label: "고양시", value: "GYEONGGI_GOYANG" },
        { label: "화성시", value: "GYEONGGI_HWASEONG" },
        { label: "성남시", value: "GYEONGGI_SEONGNAM" },
        { label: "부천시", value: "GYEONGGI_BUCHEON" },
        { label: "남양주시", value: "GYEONGGI_NAMYANGJU" },
        { label: "안산시", value: "GYEONGGI_ANSAN" },
        { label: "평택시", value: "GYEONGGI_PYEONGTAEK" },
        { label: "안양시", value: "GYEONGGI_ANYANG" },
        { label: "시흥시", value: "GYEONGGI_SIHEUNG" },
        { label: "파주시", value: "GYEONGGI_PAJU" },
        { label: "김포시", value: "GYEONGGI_GIMPO" },
        { label: "의정부시", value: "GYEONGGI_UIJEONGBU" },
        { label: "광주시", value: "GYEONGGI_GWANGJU" },
        { label: "하남시", value: "GYEONGGI_HANAM" },
        { label: "광명시", value: "GYEONGGI_GWANGMYEONG" },
        { label: "군포시", value: "GYEONGGI_GUNPO" },
        { label: "양주시", value: "GYEONGGI_YANGJU" },
        { label: "오산시", value: "GYEONGGI_OSAN" },
        { label: "이천시", value: "GYEONGGI_ICHEON" },
        { label: "안성시", value: "GYEONGGI_ANSEONG" },
        { label: "구리시", value: "GYEONGGI_GURI" },
        { label: "의왕시", value: "GYEONGGI_UIWANG" },
        { label: "포천시", value: "GYEONGGI_POCHEON" },
        { label: "양평군", value: "GYEONGGI_YANGPYEONG" },
        { label: "여주시", value: "GYEONGGI_YEOJU" },
        { label: "동두천시", value: "GYEONGGI_DONGDUCHEON" },
        { label: "과천시", value: "GYEONGGI_GWACHEON" },
        { label: "가평군", value: "GYEONGGI_GAPYEONG" },
        { label: "연천군", value: "GYEONGGI_YEONCHEON" },
    ],
    강원특별자치도: [
        { label: "춘천시", value: "GANGWON_CHUNCHEON" },
        { label: "원주시", value: "GANGWON_WONJU" },
        { label: "강릉시", value: "GANGWON_GANGNEUNG" },
        { label: "동해시", value: "GANGWON_DONGHAE" },
        { label: "태백시", value: "GANGWON_TAEBAEK" },
        { label: "속초시", value: "GANGWON_SOKCHO" },
        { label: "삼척시", value: "GANGWON_SAMCHEOK" },
        { label: "홍천군", value: "GANGWON_HONGCHEON" },
        { label: "횡성군", value: "GANGWON_HOENGSEONG" },
        { label: "영월군", value: "GANGWON_YEONGWOL" },
        { label: "평창군", value: "GANGWON_PYEONGCHANG" },
        { label: "정선군", value: "GANGWON_JEONGSEON" },
        { label: "철원군", value: "GANGWON_CHEORWON" },
        { label: "화천군", value: "GANGWON_HWACHEON" },
        { label: "양구군", value: "GANGWON_YANGGU" },
        { label: "인제군", value: "GANGWON_INJE" },
        { label: "고성군", value: "GANGWON_GOSEONG" },
        { label: "양양군", value: "GANGWON_YANGYANG" },
    ],
    충청북도: [
        { label: "청주시", value: "CHUNGBUK_CHEONGJU" },
        { label: "충주시", value: "CHUNGBUK_CHUNGJU" },
        { label: "제천시", value: "CHUNGBUK_JECHEON" },
        { label: "보은군", value: "CHUNGBUK_BOEUN" },
        { label: "옥천군", value: "CHUNGBUK_OKCHEON" },
        { label: "영동군", value: "CHUNGBUK_YEONGDONG" },
        { label: "증평군", value: "CHUNGBUK_JEUNGPYEONG" },
        { label: "진천군", value: "CHUNGBUK_JINCHEON" },
        { label: "괴산군", value: "CHUNGBUK_GOESAN" },
        { label: "음성군", value: "CHUNGBUK_EUMSEONG" },
        { label: "단양군", value: "CHUNGBUK_DANYANG" },
    ],
    충청남도: [
        { label: "천안시", value: "CHUNGNAM_CHEONAN" },
        { label: "공주시", value: "CHUNGNAM_GONGJU" },
        { label: "보령시", value: "CHUNGNAM_BORYEONG" },
        { label: "아산시", value: "CHUNGNAM_ASAN" },
        { label: "서산시", value: "CHUNGNAM_SEOSAN" },
        { label: "논산시", value: "CHUNGNAM_NONSAN" },
        { label: "계룡시", value: "CHUNGNAM_GYERYONG" },
        { label: "당진시", value: "CHUNGNAM_DANGJIN" },
        { label: "금산군", value: "CHUNGNAM_GEUMSAN" },
        { label: "부여군", value: "CHUNGNAM_BUYEO" },
        { label: "서천군", value: "CHUNGNAM_SEOCHEON" },
        { label: "청양군", value: "CHUNGNAM_CHEONGYANG" },
        { label: "홍성군", value: "CHUNGNAM_HONGSEONG" },
        { label: "예산군", value: "CHUNGNAM_YESAN" },
        { label: "태안군", value: "CHUNGNAM_TAEAN" },
    ],
    전북특별자치도: [
        { label: "전주시", value: "JEONBUK_JEONJU" },
        { label: "군산시", value: "JEONBUK_GUNSAN" },
        { label: "익산시", value: "JEONBUK_IKSAN" },
        { label: "정읍시", value: "JEONBUK_JEONGEUP" },
        { label: "남원시", value: "JEONBUK_NAMWON" },
        { label: "김제시", value: "JEONBUK_GIMJE" },
        { label: "완주군", value: "JEONBUK_WANJU" },
        { label: "진안군", value: "JEONBUK_JINAN" },
        { label: "무주군", value: "JEONBUK_MUJU" },
        { label: "장수군", value: "JEONBUK_JANGSU" },
        { label: "임실군", value: "JEONBUK_IMSIL" },
        { label: "순창군", value: "JEONBUK_SUNCHANG" },
        { label: "고창군", value: "JEONBUK_GOCHANG" },
        { label: "부안군", value: "JEONBUK_BUAN" },
    ],
    전라남도: [
        { label: "목포시", value: "JEONNAM_MOKPO" },
        { label: "여수시", value: "JEONNAM_YEOSU" },
        { label: "순천시", value: "JEONNAM_SUNCHEON" },
        { label: "나주시", value: "JEONNAM_NAJU" },
        { label: "광양시", value: "JEONNAM_GWANGYANG" },
        { label: "담양군", value: "JEONNAM_DAMYANG" },
        { label: "곡성군", value: "JEONNAM_GOKSEONG" },
        { label: "구례군", value: "JEONNAM_GURYE" },
        { label: "고흥군", value: "JEONNAM_GOHEUNG" },
        { label: "보성군", value: "JEONNAM_BOSEONG" },
        { label: "화순군", value: "JEONNAM_HWASUN" },
        { label: "장흥군", value: "JEONNAM_JANGHEUNG" },
        { label: "강진군", value: "JEONNAM_GANGJIN" },
        { label: "해남군", value: "JEONNAM_HAENAM" },
        { label: "영암군", value: "JEONNAM_YEONGAM" },
        { label: "무안군", value: "JEONNAM_MUAN" },
        { label: "함평군", value: "JEONNAM_HAMPYEONG" },
        { label: "영광군", value: "JEONNAM_YEONGGWANG" },
        { label: "장성군", value: "JEONNAM_JANGSEONG" },
        { label: "완도군", value: "JEONNAM_WANDO" },
        { label: "진도군", value: "JEONNAM_JINDO" },
        { label: "신안군", value: "JEONNAM_SINAN" },
    ],
    경상북도: [
        { label: "포항시", value: "GYEONGBUK_POHANG" },
        { label: "경주시", value: "GYEONGBUK_GYEONGJU" },
        { label: "김천시", value: "GYEONGBUK_GIMCHEON" },
        { label: "안동시", value: "GYEONGBUK_ANDONG" },
        { label: "구미시", value: "GYEONGBUK_GUMI" },
        { label: "영주시", value: "GYEONGBUK_YEONGJU" },
        { label: "영천시", value: "GYEONGBUK_YEONGCHEON" },
        { label: "상주시", value: "GYEONGBUK_SANGJU" },
        { label: "문경시", value: "GYEONGBUK_MUNGYEONG" },
        { label: "경산시", value: "GYEONGBUK_GYEONGSAN" },
        { label: "의성군", value: "GYEONGBUK_UISEONG" },
        { label: "청송군", value: "GYEONGBUK_CHEONGSONG" },
        { label: "영양군", value: "GYEONGBUK_YEONGYANG" },
        { label: "영덕군", value: "GYEONGBUK_YEONGDEOK" },
        { label: "청도군", value: "GYEONGBUK_CHEONGDO" },
        { label: "고령군", value: "GYEONGBUK_GORYEONG" },
        { label: "성주군", value: "GYEONGBUK_SEONGJU" },
        { label: "칠곡군", value: "GYEONGBUK_CHILGOK" },
        { label: "예천군", value: "GYEONGBUK_YECHEON" },
        { label: "봉화군", value: "GYEONGBUK_BONGHWA" },
        { label: "울진군", value: "GYEONGBUK_ULJIN" },
        { label: "울릉군", value: "GYEONGBUK_ULLEUNG" },
    ],
    경상남도: [
        { label: "창원시", value: "GYEONGNAM_CHANGWON" },
        { label: "진주시", value: "GYEONGNAM_JINJU" },
        { label: "통영시", value: "GYEONGNAM_TONGYEONG" },
        { label: "사천시", value: "GYEONGNAM_SACHEON" },
        { label: "김해시", value: "GYEONGNAM_GIMHAE" },
        { label: "밀양시", value: "GYEONGNAM_MIRYANG" },
        { label: "거제시", value: "GYEONGNAM_GEOJE" },
        { label: "양산시", value: "GYEONGNAM_YANGSAN" },
        { label: "의령군", value: "GYEONGNAM_UIRYEONG" },
        { label: "함안군", value: "GYEONGNAM_HAMAN" },
        { label: "창녕군", value: "GYEONGNAM_CHANGNYEONG" },
        { label: "고성군", value: "GYEONGNAM_GOSEONG" },
        { label: "남해군", value: "GYEONGNAM_NAMHAE" },
        { label: "하동군", value: "GYEONGNAM_HADONG" },
        { label: "산청군", value: "GYEONGNAM_SANCHEONG" },
        { label: "함양군", value: "GYEONGNAM_HAMYANG" },
        { label: "거창군", value: "GYEONGNAM_GEOCHANG" },
        { label: "합천군", value: "GYEONGNAM_HAPCHEON" },
    ],
    제주특별자치도: [
        { label: "제주시", value: "JEJU_JEJU" },
        { label: "서귀포시", value: "JEJU_SEOGWIPO" },
    ],
};
